export const LOAD_REPOSITORIES_REQUEST = "LOAD_REPOSITORIES_REQUEST";
export const LOAD_REPOSITORIES_SUCCESS = "LOAD_REPOSITORIES_SUCCESS";
export const LOAD_REPOSITORIES_FAILURE = "LOAD_REPOSITORIES_FAILURE";

export const CREATE_REPOSITORY_REQUEST = "CREATE_REPOSITORY_REQUEST";
export const CREATE_REPOSITORY_SUCCESS = "CREATE_REPOSITORY_SUCCESS";
export const CREATE_REPOSITORY_FAILURE = "CREATE_REPOSITORY_FAILURE";

export const UPDATE_REPOSITORY_REQUEST = "UPDATE_REPOSITORY_REQUEST";
export const UPDATE_REPOSITORY_SUCCESS = "UPDATE_REPOSITORY_SUCCESS";
export const UPDATE_REPOSITORY_FAILURE = "UPDATE_REPOSITORY_FAILURE";

export const DELETE_REPOSITORY_REQUEST = "DELETE_REPOSITORY_REQUEST";
export const DELETE_REPOSITORY_SUCCESS = "DELETE_REPOSITORY_SUCCESS";
export const DELETE_REPOSITORY_FAILURE = "DELETE_REPOSITORY_FAILURE";

export const SET_SELECTED_REPO = "SET_SELECTED_REPO";
export const SET_ACTIVE_DIALOG = "SET_ACTIVE_DIALOG";
